title: V2EX 每日热点回顾
description: Daily V2EX API 2.0 yesterday report, excluding 二手交易 and 推广.
timezone: Asia/Shanghai
lang: zh-CN
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/
plugins:
  - jekyll-feed
exclude:
  - README.md
